### ISSUE TITLE
Launch a game

### ISSUE THREAD

**Issue by RhesusP** [RRebois/ft_transcendence#24]
**Description**

Choices for local match :
- 1v1 (against bot) where stats can be taken into account
- 1v1 (against a guest on the same keyboard)

Choices for online match :
- 1v1
- 2v2 (teams are made up in order of arrival. Player 1 is with player 2 and player 3 is with player 4).

**TODO**
- [ ] Remove the "create a game button". User only have the choice to "play". A match is created if none exists with the same parameters, it joins one.
- [ ] Implement a modal to choose the match parameters (local/online and number of players
- [ ] Link it with backend
